//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartSchoolLifeAPI
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SmartSchoolsEntities2 : DbContext
    {
        public SmartSchoolsEntities2()
            : base("name=SmartSchoolsEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ScheduledBusTrip> ScheduledBusTrips { get; set; }
        public virtual DbSet<WebUser> WebUsers { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<SchoolBranch> SchoolBranches { get; set; }
        public virtual DbSet<BusInfo> BusInfoes { get; set; }
        public virtual DbSet<Notification> Notifications { get; set; }
        public virtual DbSet<DeviceRegistrar> DeviceRegistrars { get; set; }
        public virtual DbSet<AttendanceType> AttendanceTypes { get; set; }
        public virtual DbSet<Attendance> Attendances { get; set; }
        public virtual DbSet<CustomPropertyType> CustomPropertyTypes { get; set; }
        public virtual DbSet<DocumentCustomProperty> DocumentCustomProperties { get; set; }
        public virtual DbSet<Document> Documents { get; set; }
        public virtual DbSet<DocumentType> DocumentTypes { get; set; }
        public virtual DbSet<DocumrntCustomizedProperty> DocumrntCustomizedProperties { get; set; }
        public virtual DbSet<SocialMediaRole> SocialMediaRoles { get; set; }
        public virtual DbSet<SocialMediaUser> SocialMediaUsers { get; set; }
        public virtual DbSet<SocialMediaUserRole> SocialMediaUserRoles { get; set; }
        public virtual DbSet<AbsenceReason> AbsenceReasons { get; set; }
        public virtual DbSet<StudentSchoolDetail> StudentSchoolDetails { get; set; }
        public virtual DbSet<SystemSetting> SystemSettings { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
