//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartSchoolLifeAPI
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    public class CustomDateTimeConverter : IsoDateTimeConverter
    {
        public CustomDateTimeConverter()
        {
            DateTimeFormat = "dd/MM/yyyy h:mm:ss tt"; // Define your desired date format
        }
    }

    public partial class Notification
    {
        [JsonConverter(typeof(CustomDateTimeConverter))]
        public Nullable<System.DateTime> DateRead { get; set; }

        [JsonConverter(typeof(CustomDateTimeConverter))]
        public Nullable<System.DateTime> DateReceived { get; set; }

        [JsonConverter(typeof(CustomDateTimeConverter))]
        public Nullable<System.DateTime> DateSent { get; set; }
        public string DesitinationID { get; set; }
        public Nullable<int> DestinationType { get; set; }
        public Nullable<int> ImportanceLevel { get; set; }
        public int NotificationID { get; set; }
        public string NotificationText { get; set; }
        public Nullable<int> SchoolID { get; set; }
        public string SchoolYear { get; set; }
        public string SourceID { get; set; }
        public Nullable<int> SourceType { get; set; }
        public Nullable<int> Status { get; set; }

        [JsonConverter(typeof(CustomDateTimeConverter))]
        public Nullable<System.DateTime> DateDelegated { get; set; }

        [JsonConverter(typeof(CustomDateTimeConverter))]
        public Nullable<System.DateTime> DateSeen { get; set; }

        [JsonConverter(typeof(CustomDateTimeConverter))]
        public Nullable<System.DateTime> DateReplied { get; set; }
        public Nullable<int> NotificationTypeID { get; set; }
    }
}
